spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  application:
    name: bus-server
server:
  port: 8767
logging:
  level: debug
#logging.level.org.springframework.web=DEBUG