eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
server:
  port: 8765
spring:
  application:
    name: zull-server
zuul:
  routes:
    api:
      path: /api/**
      serviceId: eureka-discovery