eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
server:
  port: 8764
spring:
  application:
    name: consumer-client
  cloud:
    config:
      enabled:

#feign:
#  hystrix:
#    enabled:true
feign:
  hystrix:
    enabled: true
